In [2]:
import numpy as np 
import scipy.linalg as la

# Linear Span & Independence

Vectors are **linearly independent** if the zero vector can only be represented as trivial (=*0) linear combination.

Linearly Dependent:
- For Square Matrix: if Matrix is Singular, meaning Determinant is 0.

**Linearly Independent**:
- If Zero Vector can only be represented as trivial (*0) linear combination.
- For Square Matrix: if Matrix is Regular, meaning Determinant != 0

- If there are Pivots in every column in Row Echelon Form. So if rank A = nr. columns of A, then it's linearly independent.

In [4]:
# define base vectors
w1 = np.matrix([[0,1,2]]).T
w2 = np.matrix([[1,0,4]]).T

# matrix
B = np.hstack([w1,w2])

rkB = np.linalg.matrix_rank(B) 
rkB

2

### Find matrix of L with respect to a different basis

In [9]:
# the given transformation matrix of L
A = np.array([[1,0, 2], [5, 3, 1], [5, 3, 2]])

A = np.array([[0.5, 0.5], [-0.5, 1.5]])

# the new basis

v1 = np.array([[3],[-5], [0]])
v2 = np.array([[0],[5], [-5]])
v3 = np.array([[1],[0], [0]])

v1 = np.array([[1],[1]])
v2 = np.array([[-1],[1]])

# combine basis vectors to matrix

# V = np.hstack([v1,v2, v3])

V = np.hstack([v1,v2])

# 1.) get the image of each basis vector 
Lv1 = A@v1 
Lv2 = A@v2
# Lv3 = A@v3

# 2.) find the coordinates of each image - still unsure how to verbalize

b1 = la.solve(V,Lv1)
b2 = la.solve(V,Lv2)
# b3 = la.solve(V,Lv3)

# the coordinate vectors of the images form # the new matrix of L w.r.t. the basis v1, v2

B = np.hstack([b1,b2])

B

array([[1., 1.],
       [0., 1.]])

# Invertible Maps

A Matrix is regular if it's determinant is not zero. That means it's also invertible.

In [20]:
#inverse matrix of B

B = np.array([[1, -3], [2, -3]])

Binv = la.inv(B)
print(Binv)

[[-1.          1.        ]
 [-0.66666667  0.33333333]]


# Eigendecomposition (Eigenvalues etc.) with Python 

In [22]:
import numpy as np
import scipy.linalg as la

A = np.array ([[1 ,2, 2] , [-2, 5, 2], [5, -5, -2]])

ev , S = np.linalg.eig(A) 
print('Eigenvalues', ev)
print('Eigenvectors', S)

Eigenvalues [15.  5.]
Eigenvectors [[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]


Then we might check Eigendecomposition:

In [17]:
print(la.inv(S)@A@S)

[[15.  0.]
 [ 0.  5.]]


### Gram-Schmidt
Is done by np.linalg.qr . Note that an orthonormal basis is not unique and may differ from calculations by hand. You may even start with any vector when calculating by hand.

In [11]:
# vectors defining given subspace

w1 = np.array([[-1], [1], [5]])

w2 = np.array([[-2], [-5], [0]])

w3 = np.array([[-2], [-4], [5]])

# combine vectors to matrix

A = np.hstack([w1, w2, w3])

# get new orthonormal basis as column vectors of Q

Q,R = np.linalg.qr(A)

Q

array([[-0.19245009, -0.39429611,  0.89860644],
       [ 0.19245009, -0.91310678, -0.35944258],
       [ 0.96225045,  0.10376213,  0.2516098 ]])

Find the coordinate vector c of v with respect to the ONB u 1, u 2, u 3from Part (a).

In [13]:
# Assign the first column of the matrix Q to the variable u1
u1 = Q[:,0] 
# Changing the shape of the u1 variable to be a 3x1 matrix
u1.shape = [3,1] 
# Assign the second column of the matrix Q to the variable u2
u2 = Q[:,1] 
# Changing the shape of the u2 variable to be a 3x1 matrix
u2.shape = [3,1] 
# Assign the third column of the matrix Q to the variable u3
u3 = Q[:,2] 
# Changing the shape of the u3 variable to be a 3x1 matrix
u3.shape = [3,1] 
# Assign a 3x1 matrix to the variable v with the values [-0.7, -4.5, -5]
v = np.array([[-0.7],[-4.5],[-5]]) 
# calculates the dot product of v transpose and u1,u2 and u3 and assigns the result to c
c = np.array([[(v.T@u1)[0,0]],[(v.T@u2)[0,0]],[(v.T@u3)[0,0]]])

# Prints the matrix c
print(c)

[[-5.54256258]
 [ 3.86617713]
 [-0.26958193]]
